name: Dependency Review
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*/spec/fixtures/**'
      - '*/helpers/test/*/fixtures/**'
      - 'common/lib/dependabot.rb'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Perform Dependency Review
        uses: actions/dependency-review-action@0c155c5e8556a497adf53f2c18edabf945ed8e70 # v4.3.2
